version: "3.9"
services:
  react-app-template:
    container_name: react-app-template
    image: react-app-template
    restart: unless-stopped
    build:
      context: .
      args:
        - BUILD=local
    ports:
      - 5000:80
