const en = {
    title: "title",
    back: "back",
    left1: "DTGO provides a channel for complaints and whistleblowing for anyone who encounters or becomes aware of any action or behavior that",
    left2: "Violates the law or DTGO’s policies, rules, code of conduct, and regulations.",
    left3: "Constitutes fraud or corruption or exploitation.",
    left4: "Involves authority being exercised improperly for personal benefit or for the benefit of others.",
    left5: "Damages an individual to deter whistleblowing, cooperating in investigations, or refusing to engage in corruption.",
    left6: "Whistleblowing and Complaint System",
    left7: "Complaint Page",
    left8: "Checking status of complaint",
    left9: "Channels for Whistleblowing or Complaints",
    left10: "Call 02-742-9141 ext. 5559 ",
    left11: "(Head of Internal Audit)",
    left12: "Chairman of the DTGO Board of Directors",
    left13: "Chairman of the DTGO Executive Committee",
    left14: "Chairman of the Audit Committee",
    left15: "Business Group Chairman of Property Business",
    left16: "Business Group Chairman of Corporate Strategy & Innovative Business",
    left17: "Business Group Chairman of Corporate Finance & Marketing",
    left18: "Business Group Chairman of Culture & Corporate Management",
    left19: "Head of Internal Audit",
    left20: "Mail the whistleblowing and complaints authority directly at",
    left21: "DTGO, 695 Soi Sukhumvit 50, Sukhumvit Road,",
    left22: "Phra Khanong, Khlong",
    left23: "Toei, Bangkok 10260",
    left24: "Website https://whistleblowing.dtgo.com/",
    right1: "DT Group of Companies Whistleblowing and Complaint System",
    right2: "Please provide personal information of whistleblower or Complainant",
    right3: "Name",
    right4: "Surname",
    right5: "E-mail Address",
    right6: "Telephone /Mobile *",
    right7: "Address",
    right8: "Sub-District",
    right9: "District",
    right10: "Province",
    right11: "Post Code",
    right12: "Category of person being complained against *",
    right13: "Intended recipient of your whistleblowing or complaint *",
    right14: "Complaint Details *",
    right15: "Attach file",
    right16: "Noitems",
    right17: "SUBMIT",
    right18: "DTGO members",
    right19: "Head of Internal Audit of DTGO",
    right20: "Member of Audit Committee of DTGO",
    right21: "Executive Committee of DTGO",
    right22: "Chairman of Audit Committee of DTGO",
    right23: "Group Chief Executive Officer of DTGO",
    right24: "Head of Internal Audit of DTGO",
    footer1: "Your information will be kept strictly confidential by limiting its disclosure to those responsible for factual investigation. Please complete the form with your name and surname, phone number, and email address. This information can help us investigate your complaint. Investigations will be based on fact and may be impeded by fraudulent and anonymous complaints.",
    footer2: "Please fill in your details for the benefit of reporting the result of the operation. However, your information will be kept confidential and comply with",
    footer3: "announcement and policy related to Whistleblowing or Complaints of DTGO",
    footer4: "and",
    footer5: "Privacy Policy",
    footer6: "For more information, please call the Head of Internal Audit",
    footer7: "on 02-742 9141 ext. 5559",
    right25: "You can check the status of your complaint here",
    right26: "Please give your tracking number",
    right27: "Tracking number *",
}
const th = {
    title: "หัวข้อ",
    back: "กลับ",
    left1: "กลุ่มบริษัทดีทีจีโอ จัดให้มีช่องทางการแจ้งเบาะแส หรือข้อร้องเรียน กรณีหากมีข้อสงสัยหรือพบเห็นการกระทำ ดังนี้",
    left2: "การกระทำที่ไม่เป็นไปตามกฎหมาย นโยบาย หลักเกณฑ์ กฎระเบียบ วิธีปฏิบัติ ข้อบังคับของกลุ่มบริษัทดีทีจีโอ",
    left3: "การกระทำที่เข้าข่ายการทุจริตหรือการคอร์รัปชัน",
    left4: "การใช้หรือละเว้นการใช้อำนาจหน้าที่ เพื่อผลประโยชน์ตนเอง ครอบครัว หรือผู้อื่น",
    left5: "การกระทำใดที่เป็นผลกระทบจากการแจ้งเบาะแส หรือการให้ข้อมูล หรือการให้ความร่วมมือในการค้นหาความจริงหรือการปฏิเสธการทุจริตคอร์รัปชัน",
    left6: "ระบบการแจ้งเบาะแสและข้อร้องเรียน",
    left7: "การร้องเรียน",
    left8: "ตรวจสอบสถานะ",
    left9: "ช่องทางการติดต่อ",
    left10: "เบอร์โทรศัพท์ 02-742-9141 ต่อ 5559",
    left11: "(หัวหน้างานตรวจสอบภายใน)",
    left12: "ประธานกรรมการบริษัท บริษัท ดีทีจีโอ คอร์ปอเรชั่น จำกัด",
    left13: "ประธานกรรมการบริหาร บริษัท ดีทีจีโอ คอร์ปอเรชั่น จำกัด",
    left14: "ประธานกรรมการตรวจสอบ",
    left15: "ประธานกลุ่มธุรกิจ ธุรกิจอสังหาริมทรัพย์",
    left16: "ประธานกลุ่มธุรกิจ กลยุทธ์องค์กรและธุรกิจเชิงนวัตกรรม",
    left17: "ประธานกลุ่มธุรกิจ การเงินและการตลาดองค์กร",
    left18: "ประธานกลุ่มธุรกิจ วัฒนธรรมและการบริหารองค์กร",
    left19: "หัวหน้างานตรวจสอบภายใน",
    left20: "ไปรษณีย์ ระบุหน้าซองถึงผู้รับเรื่องการแจ้งเบาะแสหรือข้อร้องเรียนท่านใดท่านหนึ่งและตามด้วยที่อยู่",
    left21: "บริษัท ดีทีจีโอ คอร์ปอเรชั่น จำกัด เลขที่ 695 ซอย",
    left22: "สุขุมวิท 50 แขวงพระโขนง เขตคลองเตย",
    left23: "กรุงเทพมหานคร 10260",
    left24: "เว็บไซต์ https://whistleblowing.dtgo.com/",
    right1: "ระบบการแจ้งเบาะแสและข้อร้องเรียน กลุ่มบริษัทดีที",
    right2: "โปรดกรอกข้อมูลของผู้แจ้งเบาะแสหรือข้อร้องเรียน",
    right3: "ชื่อ",
    right4: "นามสกุล",
    right5: "อีเมล",
    right6: "หมายเลขโทรศัพท์ *",
    right7: "ที่อยู่",
    right8: "ตำบล",
    right9: "อำเภอ",
    right10: "จังหวัด",
    right11: "รหัสไปรษณีย์",
    right12: "กรุณาเลือกบุคคลที่ต้องการร้องเรียน",
    right13: "กรุณาเลือกบุคคลผู้รับแจ้งเบาะแสหรือข้อร้องเรียน",
    right14: "รายละเอียด *",
    right15: "เอกสารประกอบ",
    right16: "ไม่ได้แนบไฟล์",
    right17: "ยืนยัน",
    right18: "สมาชิกองศ์กร กลุ่มบริษัทดีที",
    right19: "หัวหน้างานตรวจสอบภายใน กลุ่มบริษัทดีที",
    right20: "กรรมการตรวจสอบ กลุ่มบริษัทดีที",
    right21: "ประธานกรรมการบริหาร กลุ่มบริษัทดีที",
    right22: "ประธานกรรมการตรวจสอบ กลุ่มบริษัทดีที",
    right23: "ประธานเจ้าหน้าที่บริหาร กลุ่มบริษัทดีที",
    right24: "หัวหน้างานตรวจสอบภายใจ กลุ่มบริษัทดีที",
    footer1: "กลุ่มบริษัทดีที จะเก็บรักษาข้อมูลนี้ไว้เป็นความลับ โดยจำกัดอำนาจเฉพาะผู้รับผิดชอบในการดำเนินการตรวจสอบเรื่องร้องเรียนเท่านั้น  ผู้แจ้งเบาะแสหรือผู้ร้องเรียน ควรกรอกข้อมูลและรายละเอียดต่างๆในแบบฟอร์มให้ชัดเจนและเพียงพอ รวมทั้ง แจ้งชื่อ นามสกุล หมายเลขโทรศัพท์หรืออีเมล (ถ้ามี) ที่สามารถติดต่อกลับได้ เพื่อที่ผู้ดำเนินการสามารถสอบถามข้อมูลเพิ่มเติม เพื่อประโยชน์ในการตรวจสอบข้อเท็จจริง การดำเนินการตรวจสอบตามข้อร้องเรียน จะพิจารณาจากข้อเท็จจริงที่มีความน่าเชื่อถือเท่านั้น การแจ้งเบาะแสหรือการร้องเรียนโดยไม่สุจริต หรือไม่เปิดเผยชื่อผู้แจ้งเบาะแสหรือผู้ร้องเรียน อาจเป็นข้อจำกัดในการตรวจสอบข้อเท็จจริงขององค์กร ",
    footer2: "โปรดกรอกรายละเอียดของท่าน เพื่อประโยชน์ในการแจ้งผลการดำเนินการ ทั้งนี้ข้อมูลของท่านจะถูกเก็บรักษาไว้เป็นความลับและดำเนินการภายใต้",
    footer3: "ประกาศหรือระเบียบเรื่องการแจ้งเบาะแสหรือข้อร้องเรียน กลุ่มบริษัทดีทีจีโอ",
    footer4: "และ",
    footer5: "นโยบายรักษาความเป็นส่วนตัว",
    footer6: "สอบถามข้อมูลเพิ่มเติม โปรดติดต่อ หัวหน้างานตรวจสอบภายใน",
    footer7: "เบอร์โทรศัพท์ 02-742-9141 ต่อ 5559",
    right25: "ตรวจสอบสถานะการแจ้งเบาะแสหรือข้อร้องเรียน",
    right26: "กรุณากรอกรหัสการติดตาม",
    right27: "รหัสการติดตาม *",

}
export const textKey = {
    TITLE: "title",
    BACK: "back",
    LEFT1: "left1",
    LEFT2: "left2",
    LEFT3: "left3",
    LEFT4: "left4",
    LEFT5: "left5",
    LEFT6: "left6",
    LEFT7: "left7",
    LEFT8: "left8",
    LEFT9: "left9",
    LEFT10: "left10",
    LEFT11: "left11",
    LEFT12: "left12",
    LEFT13: "left13",
    LEFT14: "left14",
    LEFT15: "left15",
    LEFT16: "left16",
    LEFT17: "left17",
    LEFT18: "left18",
    LEFT19: "left19",
    LEFT20: "left20",
    LEFT21: "left21",
    LEFT22: "left22",
    LEFT23: "left23",
    LEFT24: "left24",
    RIGHT1: "right1",
    RIGHT2: "right2",
    RIGHT3: "right3",
    RIGHT4: "right4",
    RIGHT5: "right5",
    RIGHT6: "right6",
    RIGHT7: "right7",
    RIGHT8: "right8",
    RIGHT9: "right9",
    RIGHT10: "right10",
    RIGHT11: "right11",
    RIGHT12: "right12",
    RIGHT13: "right13",
    RIGHT14: "right14",
    RIGHT15: "right15",
    RIGHT16: "right16",
    RIGHT17: "right17",
    RIGHT18: "right18",
    RIGHT19: "right19",
    RIGHT20: "right20",
    RIGHT21: "right21",
    RIGHT22: "right22",
    RIGHT23: "right23",
    RIGHT24: "right24",
    FOOTER1: "footer1",
    FOOTER2: "footer2",
    FOOTER3: "footer3",
    FOOTER4: "footer4",
    FOOTER5: "footer5",
    FOOTER6: "footer6",
    FOOTER7: "footer7",
    RIGHT25: "right25",
    RIGHT26: "right26",
    RIGHT27: "right27",
}






export const getTextResult = (key) => {

    const lang = localStorage.getItem('language')

    if (lang == "th") {
        return th[key]
    } else {
        return en[key]
    }

}